
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.VPaned vpaned2;
	private global::Gtk.Label label1;
	private global::GtkControl.MVPanel mvpanel1;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.Label label2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 170;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned2 = new global::Gtk.VPaned ();
		this.vpaned2.CanFocus = true;
		this.vpaned2.Name = "vpaned2";
		this.vpaned2.Position = 28;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.vpaned2.Add (this.label1);
		global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.label1]));
		w1.Resize = false;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.mvpanel1 = new global::GtkControl.MVPanel ();
		this.mvpanel1.Events = ((global::Gdk.EventMask)(768));
		this.mvpanel1.Name = "mvpanel1";
		this.vpaned2.Add (this.mvpanel1);
		this.hpaned1.Add (this.vpaned2);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned2]));
		w3.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 49;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.vpaned1.Add (this.label2);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.label2]));
		w4.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.vpaned1.Add (this.GtkScrolledWindow);
		this.hpaned1.Add (this.vpaned1);
		this.Add (this.hpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 675;
		this.DefaultHeight = 464;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.mvpanel1.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnMvpanel1KeyPressEvent);
		this.mvpanel1.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnMvpanel1KeyReleaseEvent);
		this.mvpanel1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnMvpanel1ButtonPressEvent);
		this.mvpanel1.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnMvpanel1ButtonReleaseEvent);
	}
}
